services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  backend:
    image: backend:transcendence
    container_name: backend
    build: ./backend
    ports:
      - '8000:8000'
    networks:
      - network
    volumes:
      - backend-media:/app/media
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database

  frontend:
    image: frontend:transcendence
    container_name: frontend
    build: ./frontend
    ports:
      - '8080:8080'
      # - '3000:3000'
      - '3000'
    volumes:
      - ./frontend/:/app
      - /app/node_modules
#      - frontend-data:/app/dist
    networks:
      - network

  nginx:
    image: nginx:transcendence
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
#      - '443:443'
    networks:
      - network
#    volumes:
#      - frontend-data:/usr/share/nginx/html
    volumes:
      - backend-media:/app/media

volumes:
  frontend-data:
  backend-media:
  postgres-data:


networks:
  network:
    driver: bridge